### ISSUE TITLE
Search across multiple fields - fails

### ISSUE THREAD

**Issue by VinothiniBalakrishnan** [swiftype/swiftype-app-search-ruby#28]
I have so many fields in my Swiftype engine. I want search across fields. I tried like

```
host_identifier = 'host-XXXX'
api_key = 'search-XXXXX'
client = SwiftypeAppSearch::Client.new(host_identifier: host_identifier, api_key: api_key)
engine_name = 'XXXXX'
queries = ["query" => {"desired_location" => "california"}, "query" => {"job_search_status" => "not_looking"}]  
options = {
    result_fields: {
      id: {raw: {}},
      email: {raw: {}}
    }
  }  
response = client.multi_search(engine_name, queries, options)
```

Getting `NoMethodError - undefined method multi_search for #<SwiftypeAppSearch::Client:0x00007f8794a0af00>`:

https://swiftype.com/documentation/app-search/api/search#multi  >> Based on this we have to use multi_search right?

**Comment by JasonStoltz** [comment]
@VinothiniBalakrishnan Hi Vinothini. The API client unfortunately doesn't support the `multi_search` endpoint yet. I will update the client and should be able to push an update in the next day or two.

**Comment by JasonStoltz** [comment]
@VinothiniBalakrishnan You can now do this in v0.4.0. Your syntax will need to change to:

```ruby
host_identifier = 'host-XXXX'
api_key = 'search-XXXXX'
client = SwiftypeAppSearch::Client.new(host_identifier: host_identifier, api_key: api_key)
engine_name = 'XXXXX'
queries = [{
  :query => 'california',
  :options => { 
    :search_fields => { :desired_location => {} },
    :result_fields => { id: {raw: {}}, email: {raw: {}} }
  }
},{
  :query => 'job_search_status',
  :options => { 
    :search_fields => { :job_search_status => {} },
    :result_fields => { id: {raw: {}}, email: {raw: {}} }
  }
}]
response = client.multi_search(engine_name, queries)
```

**Comment by VinothiniBalakrishnan** [comment]
@JasonStoltz Thank you so much for the update. Works fine.  

Can you please clarify me one thing. I have 500+ records. 
Let’s say we are searching for candidates with the following criteria 

A. Role: Accountant AND BookKeeper
B. Location: East Bay OR San Francisco 

Let’s say that Criteria A results are
Thiru
Vinothini 
Sandeep

Let’s say Criteria B results are
Kavitha
Thiru
Anandhi
Sandeep
Nancy 

So, the end result of criteria A + B is the candidates that are common in both these results. 
Thiru
Sandeep 

1. Swiftype won't Thiru and Sandeep is my final result? do we have to filter it ?
2. If answer is YES for question1 how to handle with pagination?



`[{"meta"=>{"warnings"=>[], "page"=>{"current"=>1, "total_pages"=>1, "total_results"=>3, "size"=>10}, "request_id"=>"ba935dfbee3ba8e3663de4b9a9a2267a"}, "results"=>[{"email"=>{"raw"=>"vinothinib+58@spritle.com"}, "id"=>{"raw"=>"8"}, "_meta"=>{"score"=>3.0969055}}, {"email"=>{"raw"=>"vinothinib+52@spritle.com"}, "id"=>{"raw"=>"2"}, "_meta"=>{"score"=>3.0969055}}, {"email"=>{"raw"=>"sweetyphilo1994+24@gmail.com"}, "id"=>{"raw"=>"34"}, "_meta"=>{"score"=>0.027618442}}]}, {"meta"=>{"warnings"=>[], "page"=>{"current"=>1, "total_pages"=>10, "total_results"=>96, "size"=>10}, "request_id"=>"ba935dfbee3ba8e3663de4b9a9a2267a"}, "results"=>[{"email"=>{"raw"=>"vinothinib+149@spritle.com"}, "id"=>{"raw"=>"99"}, "_meta"=>{"score"=>0.342951}}, {"email"=>{"raw"=>"vinothinib+147@spritle.com"}, "id"=>{"raw"=>"97"}, "_meta"=>{"score"=>0.342951}}, {"email"=>{"raw"=>"vinothinib+150@spritle.com"}, "id"=>{"raw"=>"100"}, "_meta"=>{"score"=>0.342951}}, {"email"=>{"raw"=>"vinothinib+148@spritle.com"}, "id"=>{"raw"=>"98"}, "_meta"=>{"score"=>0.342951}}, {"email"=>{"raw"=>"vinothinib+146@spritle.com"}, "id"=>{"raw"=>"96"}, "_meta"=>{"score"=>0.342951}}, {"email"=>{"raw"=>"vinothinib+143@spritle.com"}, "id"=>{"raw"=>"93"}, "_meta"=>{"score"=>0.342951}}, {"email"=>{"raw"=>"vinothinib+145@spritle.com"}, "id"=>{"raw"=>"95"}, "_meta"=>{"score"=>0.342951}}, {"email"=>{"raw"=>"vinothinib+144@spritle.com"}, "id"=>{"raw"=>"94"}, "_meta"=>{"score"=>0.342951}}, {"email"=>{"raw"=>"vinothinib+140@spritle.com"}, "id"=>{"raw"=>"90"}, "_meta"=>{"score"=>0.342951}}, {"email"=>{"raw"=>"vinothinib+141@spritle.com"}, "id"=>{"raw"=>"91"}, "_meta"=>{"score"=>0.342951}}]}]
`
