### ISSUE TITLE
Multi search error message

### ISSUE THREAD

**Issue by VinothiniBalakrishnan** [swiftype/swiftype-app-search-ruby#38]
```
  def talent_search
    client = SwiftypeAppSearch::Client.new(host_identifier: ENV["SWIFTYPE_HOST_IDENDIFIER"], api_key: ENV["SWIFTYPE_SEARCH_KEY"])
    engine_name = ENV["SWIFTYPE_ENGINE_NAME"]
    query_val   = []
    arr         = []
    form_data   = JSON.parse(params["data"].to_json)
    form_data.each{|x| arr.push(x[1]) } unless form_data.nil?

    if params["data"]
      params["data"].each do |data|        
        operation = operation_decision(arr, data[1]["type"] + "_check")
        query_val.push({data[1]["type"] => data[1]["values"].map!{|word|  "\""+word+"\""}.join(operation)})
      end
    end

    queries = [
      {:query => query_select(query_val, "roles_intersted_in"),
      :options => { 
        :page => {size: 1000},
        :search_fields => { :roles_intersted_in => {} },
        :result_fields => { id: {raw: {}}, email: {raw: {}} }}
      },
      {:query => query_select(query_val, "company_size"),
        :options => { 
          :search_fields => { :company_size => {} },
          :result_fields => { id: {raw: {}}, email: {raw: {}} }}
      },
      {:query => query_select(query_val, "software_experience"),
        :options => { 
          :search_fields => { :software_experience => {} },
          :result_fields => { id: {raw: {}}, email: {raw: {}} }}
      },
      {:query => query_select(query_val, "certifications"),
        :options => { 
          :search_fields => { :certifications => {} },
          :result_fields => { id: {raw: {}}, email: {raw: {}} }}
      },
      {:query => query_select(query_val, "company_size_interested_in"),
        :options => { 
          :search_fields => { :company_size_interested_in => {} },
          :result_fields => { id: {raw: {}}, email: {raw: {}} }}
      },
      {:query => query_select(query_val, "desired_location"),
        :options => { 
          :search_fields => { :desired_location => {} },
          :result_fields => { id: {raw: {}}, email: {raw: {}} }}
      },
      {:query => query_select(query_val, "full_time_role"),
        :options => { 
          :search_fields => { :full_time_role => {} },
          :result_fields => { id: {raw: {}}, email: {raw: {}} }}
      },
      {:query => query_select(query_val, "type_of_employment"),
        :options => { 
          :page => {size: 1000},
          :search_fields => { :type_of_employment => {} },
          :result_fields => { id: {raw: {}}, email: {raw: {}} }}
      },
      {:query => query_select(query_val, "years_experience"),
        :options => { 
          :page => {size: 1000},
          :search_fields => { :years_experience => {} },
          :result_fields => { id: {raw: {}}, email: {raw: {}} }}
       },
       {:query => query_select(query_val, "industry_experience"),
        :options => {
          :page => {size: 1000},
          :search_fields => { :industry_experience => {} },
          :result_fields => { id: {raw: {}}, email: {raw: {}} }}
      }#,
      # {:query => query_select(query_val, "degree"),
      #   :options => { 
      #     :search_fields => { :degree => {} },
      #     :result_fields => { id: {raw: {}}, email: {raw: {}} }}
      # },
      # {:query => query_select(query_val, "skills"),
      #   :options => { 
      #     :search_fields => { :skills => {} },
      #     :result_fields => { id: {raw: {}}, email: {raw: {}} }}
      # },
      # {:query => query_select(query_val, "require_sponsorship"),
      # :options => { s
      #     :search_fields => { :require_sponsorship => {} },
      #     :result_fields => { id: {raw: {}}, email: {raw: {}} }}
      # },
      # {:query => query_select(query_val, "major"),
      # :options => { 
      #     :search_fields => { :major => {} },
      #     :result_fields => { id: {raw: {}}, email: {raw: {}} }}
      # }
    ]

    p queries, '-----queries-----'

    begin
      response = client.multi_search(engine_name, queries)
      p response, '----- SWIFTYPE RESPONSE -----'
      candidate_ids = []
      response.each_with_index do|res, index|
        candidate_ids.push(res["results"].map{|x| x["id"]["raw"]})
      end
      candidate_ids = candidate_ids.inject(&:&)
      candidates = Candidate.where(id: candidate_ids)   
      render :json => {:success => true, candidates: candidates}
    rescue SwiftypeAppSearch::ClientException => e
      puts e
      p '==================='
    end   
  end
```

[{:query=>"\"Accounting Manager\" OR \"Audit/Compilance\" OR \"Bookkeeper\" OR \"Controller\" OR \"Director of Finance\" OR \"Finance Manager\" OR \"Finance Analyst\" OR \"Financial Reporting / SEC\" OR \"Principal Analyst\" OR \"Payroll\" OR \"Revenue\" OR \"Senior Accountant\" OR \"Senior Financial Analyst\" OR \"Staff accountant\" OR \"Tax\"", :options=>{:page=>{:size=>1000}, :search_fields=>{:roles_intersted_in=>{}}, :result_fields=>{:id=>{:raw=>{}}, :email=>{:raw=>{}}}}}, {:query=>"", :options=>{:search_fields=>{:company_size=>{}}, :result_fields=>{:id=>{:raw=>{}}, :email=>{:raw=>{}}}}}, {:query=>"", :options=>{:search_fields=>{:software_experience=>{}}, :result_fields=>{:id=>{:raw=>{}}, :email=>{:raw=>{}}}}}, {:query=>"", :options=>{:search_fields=>{:certifications=>{}}, :result_fields=>{:id=>{:raw=>{}}, :email=>{:raw=>{}}}}}, {:query=>"", :options=>{:search_fields=>{:company_size_interested_in=>{}}, :result_fields=>{:id=>{:raw=>{}}, :email=>{:raw=>{}}}}}, {:query=>"", :options=>{:search_fields=>{:desired_location=>{}}, :result_fields=>{:id=>{:raw=>{}}, :email=>{:raw=>{}}}}}, {:query=>"", :options=>{:search_fields=>{:full_time_role=>{}}, :result_fields=>{:id=>{:raw=>{}}, :email=>{:raw=>{}}}}}, {:query=>"", :options=>{:page=>{:size=>1000}, :search_fields=>{:type_of_employment=>{}}, :result_fields=>{:id=>{:raw=>{}}, :email=>{:raw=>{}}}}}, {:query=>"", :options=>{:page=>{:size=>1000}, :search_fields=>{:years_experience=>{}}, :result_fields=>{:id=>{:raw=>{}}, :email=>{:raw=>{}}}}}, {:query=>"", :options=>{:page=>{:size=>1000}, :search_fields=>{:industry_experience=>{}}, :result_fields=>{:id=>{:raw=>{}}, :email=>{:raw=>{}}}}}]
"-----queries-----"

We are using 0.4.4 version of gem only but still error message not showing explicitly

**Comment by JasonStoltz** [comment]
Hey @VinothiniBalakrishnan,

I'm not seeing the behavior you describe.

With your first query, I'm not sure how to reproduce an error response. What do you actually see when you run that query? I tried uncommenting some queries to trigger an error:

```
irb(main):199:0> begin
irb(main):200:1>   response = client.multi_search(engine_name, queries)
irb(main):201:1> rescue SwiftypeAppSearch::ClientException => e
irb(main):202:1>   puts e
irb(main):203:1> end
Error: Queries exceeds the maximum number of 10 allowed queries
```

With your second query, I see a number of explicit errors, including "Query is too long (maximum is 64 characters)". Granted, my engine is different than yours, so our errors will differ, but I do see error messages.

```
irb(main):064:0> begin
irb(main):065:1>   response = client.multi_search(engine_name, queries)
irb(main):066:1> rescue SwiftypeAppSearch::ClientException => e
irb(main):067:1>   puts e
irb(main):068:1> end
Errors: ["Query is too long (maximum is 64 characters)", "Search fields contains invalid field: roles_intersted_in", "Result fields contains invalid field: email", "Searchfields contains invalid field: company_size", "Result fields contains invalid field: email", "Search fields contains invalid field: software_experience", "Result fields contains invalid field: email", "Search fields contains invalid field: certifications", "Result fields contains invalid field: email", "Search fields contains invalid field: company_size_interested_in", "Result fields contains invalid field: email", "Search fields contains invalid field: desired_location", "Result fields contains invalid field:email", "Search fields contains invalid field: full_time_role", "Result fields contains invalid field: email", "Search fields contains invalid field: type_of_employment", "Result fields contains invalid field: email", "Search fields contains invalid field: years_experience", "Result fields contains invalid field: email", "Search fields contains invalid field: industry_experience", "Result fields contains invalid field: email"]
```

What is the behavior you are experiencing?

**Comment by JasonStoltz** [comment]
Also, what are you trying to accomplish with this query? Perhaps there is a simpler way to query, rather than with a long OR or multi_search.

**Comment by VinothiniBalakrishnan** [comment]
@JasonStoltz we are trying multi search with AND and OR operation. 

![coredge 2](https://user-images.githubusercontent.com/970659/47836492-8047f100-ddce-11e8-8da7-f07c60abf89e.png)

I have so many filter items in page. Based on filter selection we should return the result.

Scenario 1: 
A. Roles interested in: Accountant AND BookKeeper
B. Desired location: East Bay OR San Francisco 

Let’s say that Criteria A results are
Thiru
Vinothini 
Sandeep

Let’s say Criteria B results are
Kavitha
Thiru
Anandhi
Sandeep
Nancy 

So, the end result of criteria A + B is the candidates that are common in both these results. So,app should return 
Thiru
Sandeep 

Note: 
1. Imagine Roles interested dropdown we selected Account Manager, Bookkeeper, Controller and hit apply filter dropdown, application should search who are marked the roles interested in as Account Manager OR Bookkeeper OR Controller

2. Imagine Roles interested dropdown we selected Account Manager, Bookkeeper, Controller and checked the AND checkbox above the dropdown and hit apply filter dropdown, application should search who are marked the roles interested in as Account Manager AND Bookkeeper AND Controller

![coredge 3](https://user-images.githubusercontent.com/970659/47836795-930ef580-ddcf-11e8-8959-41c403b6fe0f.png)

**Comment by JasonStoltz** [comment]
@VinothiniBalakrishnan OK, I see what you mean. Yeah, the feature you'd want to use to accomplish this is "filters", as I mentioned on your community post: https://community.swiftype.com/t/swiftype-multi-search-search-query-length-more-than-64-characters/911/4.

There is more information here: https://swiftype.com/documentation/app-search/api/search/filters

I believe you query should contain filter options like the following:

```ruby
filters: {
    all: [
      { roles_interested_in: ['Accounting Manager', 'Bookkeeper', 'Controller'] },
      { skills: ['Programming', 'Operations'] },
      { requires_sponsorship: true },
      { type_of_employment: ['Full Time', 'Contract'] }
    ]
```

See what I mean? Passing an array of values as a filter is an OR condition.

**Comment by VinothiniBalakrishnan** [comment]
@JasonStoltz I tried filter. I think this is not full fill my requirement properly. I have to perform both AND, OR operation between filter option values based on user check AND checkbox (Please refer above screenshot for where AND check box places). 
Eg: 
1. User can search who's desired_location Peninsula AND South Bay with other filters
2. User can search who's desired_location Peninsula OR South Bay with other filters

  def talent_search
    client = SwiftypeAppSearch::Client.new(host_identifier: ENV["SWIFTYPE_HOST_IDENDIFIER"], api_key: ENV["SWIFTYPE_SEARCH_KEY"])
    engine_name = ENV["SWIFTYPE_ENGINE_NAME"]
    query = ""
    options = {
      filters: {
        all: [
          {"desired_location": "Peninsula AND South Bay"},
          {"candidate_status": "new_fresh"}
        ]
      },
      result_fields: { id: {raw: {}}, email: {raw: {}} }
    }

    begin
      response = client.search(engine_name, query, options)
      p response["results"], '----- SWIFTYPE RESPONSE -----'
    rescue SwiftypeAppSearch::ClientException => e
      puts e
    end

User 1: Desired locations are Peninisula, South Bay and San Francisco
User 2: Desired locations are South Bay, East Bay and San Francisco

Scenario 1: If use selects Peninisula AND South Bay - User1 only should come
Scenrio 2:  If use selects Peninisula OR South Bay - User1 & User2 should come
Scenrio 3:  If use selects East Bay - User2 only should come

May I know how we can achieve this with filters?

**Comment by VinothiniBalakrishnan** [comment]
@JasonStoltz I am expecting query should work like

For few scenario 

```
  def talent_search
    client = SwiftypeAppSearch::Client.new(host_identifier: ENV["SWIFTYPE_HOST_IDENDIFIER"], api_key: ENV["SWIFTYPE_SEARCH_KEY"])
    engine_name = ENV["SWIFTYPE_ENGINE_NAME"]
    query = ""
    options = {
      filters: {
        all: [
          {"roles_intersted_in": "\"Accounting Manager\" AND \"Senior Financial Analyst\" AND \"Senior Accountant\" AND \"Revenue\""},
          {"require_sponsorship": "true"},
          {"candidate_status": "new_fresh"}
        ]
      },
      result_fields: { id: {raw: {}}, email: {raw: {}} }
    }
 begin
      response = client.search(engine_name, query, options)
      p response["results"], '----- SWIFTYPE RESPONSE -----'
rescue SwiftypeAppSearch::ClientException => e
      puts e
      p '==================='
    end    
```

For few scenario 

```
  def talent_search
    client = SwiftypeAppSearch::Client.new(host_identifier: ENV["SWIFTYPE_HOST_IDENDIFIER"], api_key: ENV["SWIFTYPE_SEARCH_KEY"])
    engine_name = ENV["SWIFTYPE_ENGINE_NAME"]
    query = ""
    options = {
      filters: {
        all: [
          {"roles_intersted_in": "\"Accounting Manager\" OR \"Senior Financial Analyst\" OR \"Senior Accountant\" OR \"Revenue\""},
          {"require_sponsorship": "true"},
          {"candidate_status": "new_fresh"}
        ]
      },
      result_fields: { id: {raw: {}}, email: {raw: {}} }
    }
 begin
      response = client.search(engine_name, query, options)
      p response["results"], '----- SWIFTYPE RESPONSE -----'
rescue SwiftypeAppSearch::ClientException => e
      puts e
      p '==================='
    end   
``` 
May I know the possibility for this.

**Comment by JasonStoltz** [comment]
Hey @VinothiniBalakrishnan.

If you want to AND all of the `roles_interested_in` values, it would look like this:

```ruby
all: [
  {"roles_intersted_in": "Accounting Manager"},
  {"roles_intersted_in": "Senior Financial Analyst"},
  {"roles_intersted_in": "Senior Accountant"},
  {"roles_intersted_in": "Revenue"}
  {"require_sponsorship": "true"},
  {"candidate_status": "new_fresh"}
]
```
To OR all of the `roles_interested_in` values, it would look like this:
```ruby
all: [
  {"roles_intersted_in": ["Accounting Manager", "Senior Financial Analyst", "Senior Accountant", "Revenue"]},
  {"require_sponsorship": "true"},
  {"candidate_status": "new_fresh"}
]
```
