### ISSUE TITLE
Not able to apply range filter

### ISSUE THREAD

**Issue by VinothiniBalakrishnan** [swiftype/swiftype-app-search-ruby#39]
Referred range filter and combine filter section at https://swiftype.com/documentation/app-search/api/search/filters

  ```
def talent_search
    client = SwiftypeAppSearch::Client.new(host_identifier: ENV["SWIFTYPE_HOST_IDENDIFIER"], api_key: ENV["SWIFTYPE_SEARCH_KEY"])
    engine_name = ENV["SWIFTYPE_ENGINE_NAME"]
      query = ""
    options = {
      filters: {
        all: [
          {"profile_active": "true"},
          {"desired_compensation": { from: 4000, to: 8000 } }
        ]
      },
      result_fields: { id: {raw: {}}, email: {raw: {}} }
    }

    begin
      response = client.search(engine_name, query, options)
      p response["results"], '----- SWIFTYPE RESPONSE -----'
    rescue SwiftypeAppSearch::ClientException => e
      puts e
      p '==================='
    end    
  end  
```
Getting 
`Error: Filters contains invalid value for field: desired_compensation; must be a string, or an array of strings`

Please let me know what I am missing here.

**Comment by JasonStoltz** [comment]
Hey @VinothiniBalakrishnan,

Sorry, that error message is a bit confusing. Log into your Dashboard, go to the Schema tab, and make sure that the `desired_compensation` is set to type "Number". It is likely currently "Text", which is why you see that error message.'

Jason

**Comment by VinothiniBalakrishnan** [comment]
Thanks for the hint @JasonStoltz You are right. After change type from string to number, range filter works fine
