### ISSUE TITLE
Bulk indexing calls

### ISSUE THREAD

**Issue by adityasrini** [swiftype/swiftype-app-search-ruby#51]
I don't see a way to do bulk indexing operations as documented [here](https://swiftype.com/documentation/site-search/indexing#bulk_operations). Is this supported by the library currently?

**Comment by JasonStoltz** [comment]
@adityasrini You can use the `index_documents` method for that: https://github.com/swiftype/swiftype-app-search-ruby#indexing-creating-or-replacing-documents. Just note that there is a 100 document limit on that API endpoint, so you may need to do your indexing in batches.

**Comment by adityasrini** [comment]
That's interesting. The `index_documents` method seems to call [this endpoint](https://swiftype.com/documentation/site-search/indexing#add-document). Does that endpoint process documents (up to 100) with the same speed/efficiency as a call to the bulk endpoint?

**Comment by JasonStoltz** [comment]
@adityasrini Oh, actually, I think I see the disconnect here. We have 2 products as Swiftype, App Search (https://swiftype.com/app-search) and Site Search (https://swiftype.com/site-search).

The documentation endpoint you are linking to is for Site Search, but this API client is for App Search.

If you are looking for the Site Search client, that is here: https://github.com/swiftype/swiftype-rb.

**Comment by adityasrini** [comment]
Whoops I think I didn't see the difference either. Welp, I hope there's not much to refactor in my codebase lol 🤦🏾‍♂️
